#!/bin/bash
# Generate scripts/config.sh from environment (CI / workflows).
# Required: TARGET_UBUNTU_VERSION, TARGET_KERNEL_FLAVOR
# Optional: TARGET_KERNEL_METAPACKAGE_INSTALL_RECOMMENDS (yes|no, default no)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${SCRIPT_DIR}/config.sh"

TARGET_UBUNTU_VERSION="${TARGET_UBUNTU_VERSION:?set TARGET_UBUNTU_VERSION}"
TARGET_KERNEL_FLAVOR="${TARGET_KERNEL_FLAVOR:?set TARGET_KERNEL_FLAVOR}"
TARGET_KERNEL_METAPACKAGE_INSTALL_RECOMMENDS="${TARGET_KERNEL_METAPACKAGE_INSTALL_RECOMMENDS:-no}"

case "$TARGET_UBUNTU_VERSION" in
    jammy|noble|resolute) ;;
    *)
        echo "TARGET_UBUNTU_VERSION must be jammy, noble, or resolute" >&2
        exit 1
        ;;
esac
case "$TARGET_KERNEL_FLAVOR" in
    generic|lowlatency) ;;
    *)
        echo "TARGET_KERNEL_FLAVOR must be generic or lowlatency" >&2
        exit 1
        ;;
esac
case "$TARGET_KERNEL_METAPACKAGE_INSTALL_RECOMMENDS" in
    yes|no) ;;
    *)
        echo "TARGET_KERNEL_METAPACKAGE_INSTALL_RECOMMENDS must be yes or no" >&2
        exit 1
        ;;
esac

cat > "$OUT" <<EOF
#!/bin/bash
# Generated by scripts/ci/render-config.sh — remove after build if desired
# shellcheck source=/dev/null
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
. "\${SCRIPT_DIR}/default_config.sh"
export TARGET_UBUNTU_VERSION="${TARGET_UBUNTU_VERSION}"
export TARGET_KERNEL_FLAVOR="${TARGET_KERNEL_FLAVOR}"
export TARGET_KERNEL_METAPACKAGE_INSTALL_RECOMMENDS="${TARGET_KERNEL_METAPACKAGE_INSTALL_RECOMMENDS}"
export CONFIG_FILE_VERSION="0.7"
EOF

echo "Wrote $OUT"
